- src/java/ognl/OgnlContext.java
I've optimized the `OgnlContext` constructors so that:
* The `_values` map object is not instantiated if not really needed. This map (which was a large one, 23 entries) was being always created, even if the `OgnlContext` constructor being used immediately replaced it by one of its arguments. I'm executing some thousands of OGNL expressions per second and I'm always using `new OgnlContext(myOwnMap)`, so this meant a lot of spurious, large `HashMap` objects being created without any need and a waste in memory usage.
* The `_typeStack` and `_accessorStack` objects, of type `List`, were being initialized to their default size which is `10`, but very few OGNL expressions actually use 10 stack positions. Normally they don't go over `2` or `3`. So by reducing the initial size of those …
> Optimized OgnlContext constructors, reduced collection sizes

- src/java/ognl/enhance/ExpressionCompiler.java
Most of my profiling sessions show `java.lang.Class#getInterfaces()` as one of the *hot spots* under heavy OGNL load, because of being used at several methods in `ognl.enhance.ExpressionCompiler`, especially `ognl.enhance.ExpressionCompiler#getInterfaceClass(java.lang.Class)`
Indeed it seems this `java.lang.Class#getInterfaces()` method, even if being native, is quite slow for some strange reason. I've read a couple of complaints about it also related with Hibernate (see [1] and [2]).
Fortunately, I was able to importantly reduce the amount of times this method has to be called in `ExpressionCompiler` without losing any functionality, just re-structuring a bit the code. This should save a noticeable amount of execution time.
[1] https://forum.hibernate.org/viewtopic.php?p=2404651
[2] …
> Optimized the use of java.lang.Class#getInterfaces() in OgnlCompiler

- src/java/ognl/ASTAdd.java
- src/java/ognl/ListPropertyAccessor.java
- src/java/ognl/MapPropertyAccessor.java
- src/java/ognl/ObjectPropertyAccessor.java
- src/java/ognl/OgnlRuntime.java
- src/java/ognl/enhance/ExpressionCompiler.java
Several parts of OGNL call the `java.lang.String#replaceAll(...)` method, which is extremely inefficient because it first compiles a `java.util.regex.Pattern`, then a `Matcher`, and finally asks this `Matcher` to perform the replace operation.
In order to avoid most of the calls to this method without disrupting the code base too much, I've added before each call a condition based on a call to `java.lang.String#indexOf(...)`, which is hugely more efficient because it acts directly on the `String`'s inner `char[]`. And only if this `indexOf(...)` determines there is a possibility that the `replaceAll(...)` operation would actually *do something*, `replaceAll(...)` will be called.
> Optimization: avoid using java.lang.String#replaceAll() in most cases

- src/java/ognl/OgnlRuntime.java
The current implementation of the cache for getter/setter methods in `ognl.OgnlRuntime` has three issues, mostly from the performance standpoint:
* The `Map` implementation being used for the `cacheGetMethod` and `cacheSetMethod` static variables is `java.util.HashMap`, which does not allow concurrent access. It seems that an attempt to solve this was made by adding a `synchronized {...}` block around the lines of code where new values are `put(...)` to these maps, but this is not completely correct because it would allow *read* access to those maps by a thread at the same time some other thread is inside that synchronized block modifying the map, which is a concurrency issue.
* The cache map keys are of a specialized private class called `CacheKey`, which contains two properties: `Class …
> Improved performance of getter/setter method caching in OgnlRuntime

- src/java/ognl/OgnlRuntime.java
- src/test/java/ognl/TestOgnlRuntime.java
- src/test/java/org/ognl/test/objects/OtherEnum.java
OGNL-158 Statics within Enums causing IllegalArgumentExceptions (WW-4479 Ognl can't access static field on enum)
> OGNL-158 Statics within Enums causing IllegalArgumentExceptions

- pom.xml
- src/java/ognl/ASTCtor.java
- src/java/ognl/ASTMethod.java
- src/java/ognl/OgnlRuntime.java
- src/test/java/org/ognl/test/MethodTest.java
- src/test/java/org/ognl/test/PropertyTest.java
- src/test/java/org/ognl/test/objects/MethodTestMethods.java
- src/test/java/org/ognl/test/objects/Root.java
- src/test/java/org/ognl/test/objects/Simple.java
This fixes:
#16 
#17 
https://issues.apache.org/jira/browse/OGNL-250
and maybe even more issues related to wrong methods. 
But it's a huge change in OGNL method matching so it also might break some things.
All unit tests pass for Java 7 and Java 8.
> This is the initial version of an 'java like' method matching for OGNL.

- src/java/ognl/OgnlRuntime.java
- src/test/java/ognl/Java8Test.java
Workaround for https://bugs.openjdk.java.net/browse/JDK-8071693
> Add access for property which read method is java8 default method

- pom.xml
- src/java/ognl/OgnlRuntime.java
if check permission and run synchronized on method first call in order to fix [WW-4817](https://issues.apache.org/jira/browse/WW-4817)
> WW-4817 Makes better decisions on methods first call

- src/java/ognl/OgnlRuntime.java
Makes better decisions on methods first call if check permission and run synchronized
> WW-4817 Similar to #36 for master

- src/java/ognl/OgnlRuntime.java
- src/test/java/ognl/Java8Test.java
When scanning super interfaces in `OgnlRuntime#getMethods(Class, boolean)`, only default methods should be collected instead of all declared methods.
Also, super interfaces should be searched recursively so that it can handle deeper interface hierarchy.
> Backporting #40 to ognl-3-1-x branch.

- src/main/java/ognl/DefaultClassResolver.java
The `DefaultClassResolver` is not thread-safe.
I will propose to support concurrent using `ConcurrentHashMap` on the `DefaultClassResolver`.
WDYT?
> Support concurrent on DefaultClassResolver

- src/main/java/ognl/DefaultClassResolver.java
I will propose to allow override a strategy for loading Class. Actually, the MyBatis core module want to override strategy using this extending point. Currently, we copy the `DefaultClassResolver` and modify a class loading logic.
WDYT?
> Allow override a strategy for loading Class on DefaultClassResolver

- src/java/ognl/OgnlRuntime.java
- src/test/java/ognl/Java8Test.java
getDeclaredMethods() should search super-interfaces recursively.
> Backporting #55 to ognl-3-1-x branch.

- src/java/ognl/OgnlRuntime.java
- src/test/java/ognl/Java8Test.java
This was fixed in master via #33, but was not backported to 3.1.x branch.
> getReadMethod() should check default methods as well.

- pom.xml
- src/java/ognl/DefaultMemberAccess.java
- src/test/java/org/ognl/test/PrivateMemberTest.java
Update OGNL 3.1.x build configuration, enhance unit test and cleanup restore method.
`pom.xml` changes:
- updated `maven-surefire-plugin` 2.3 -> 2.22.1
- updated `maven-clean-plugin` 2.1.1 -> 2.6.1
- updated `junit` 4.9 -> 4.12
- updated `easymock` 2.3 -> 2.5.2
- added `defaultGoal` to build
Code changes:
- added additional tests to `PrivateMemberTest` (relevant to PR#58/PR#59/PR#60)
- minor cleanup for `DefaultMemberAccess` restore method
> Update OGNL 3.1.x build configuration, enhance unit test and cleanup restore method

- pom.xml
- src/test/java/ognl/DefaultMemberAccess.java
- src/test/java/org/ognl/test/PrivateMemberTest.java
Update OGNL 3.2.x build configuration, enhance unit test and cleanup restore method.
Bring forward relevant changes from PR #61 (3.1.x)
`pom.xml` changes
- updated `maven-surefire-plugin` 2.3 -> 2.22.1
- updated `maven-clean-plugin` 2.1.1 -> 2.6.1
- updated `junit` 4.9 -> 4.12
- updated `easymock` 2.3 -> 2.5.2
- added `defaultGoal` to build
Code changes:
- added additional tests to `PrivateMemberTest` (relevant to PR#58/PR#59/PR#60)
- minor cleanup for `DefaultMemberAccess` (test-only) restore method
> Update OGNL 3.2.x build configuration, enhance unit test and cleanup restore method.

- src/java/ognl/OgnlRuntime.java
- src/test/java/org/ognl/test/PrivateMemberTest.java
- src/test/java/org/ognl/test/ProtectedMemberTest.java
- src/test/java/org/ognl/test/PublicMemberTest.java
Updates to OGNL 3.1.x `OgnlRuntime`:
Code changes:
- added clarifying comments to `getStaticField()`, cleanup.
- added a finally guard in `invokeMethod()`.
- added a finally guard in `getFieldValue()`, cleanup.
- added additional limiter (final) to `setFieldValue()`, cleanup.
- added two test units for protected and public members.
- updated `PrivateMemberTest` with additional tests, cleanup.
> Updates to OGNL 3.1.x OgnlRuntime

- pom.xml
- src/main/java/ognl/OgnlRuntime.java
- src/test/java/org/ognl/test/PrivateMemberTest.java
- src/test/java/org/ognl/test/ProtectedMemberTest.java
- src/test/java/org/ognl/test/PublicMemberTest.java
Updates to OGNL 3.2.x `OgnlRuntime`:
`pom.xml` changes:
- downgrade `javassist` 3.24.0-GA -> 3.23.1-GA, _to restore compatiblity with JDK 7_.
Code changes:
- added clarifying comments to `getStaticField()`, cleanup.
- added a finally guard in `invokeMethod()`.
- added a finally guard in `getFieldValue()`, cleanup.
- added additional limiter (final) to `setFieldValue()`, cleanup.
- added two test units for protected and public members.
- updated `PrivateMemberTest` with additional tests, cleanup.
> Updates to OGNL 3.2.x OgnlRuntime

- pom.xml
Update OGNL 3.2.x to use Javassist 3.24.1 (JDK7 compatible again).
Maven build completed without errors on JDK7 (1.7.0_79).
> Update OGNL 3.2.x to use Javassist 3.24.1 (JDK7 compatible again)

- src/java/ognl/ASTStaticField.java
- src/java/ognl/OgnlRuntime.java
Fix backwards-compatibility issue introduced with PR#59/#60
- Made access to non-public static fields _an optional opt-in feature_ (control flag via `context`).
- Restored _original behaviour when accessing public static fields_ (the default behaviour).
- Updated unit tests to test proper behaviour with both original (default) and opt-in behaviour.
> Fix backwards-compatibility issue introduced with PR#59/#60

- src/java/ognl/OgnlRuntime.java
- src/test/java/ognl/OgnlRuntimeTest.java
Proposed minor cleanup change to 3.1.x branch:
- `OgnlRuntime.invokeMethod()`:
- Eliminate a couple of unused assignments, reduce number of `get()` calls to `ConcurrentHashMap` instances by 2.
- `OgnlRuntime._getGetMethod()`: Removed one whitespace line.
- `OgnlRuntimeTest`: Added some execution time tracking and output to runTest().
- `OgnlRuntimeTest`: Added two additional tests involving a larger set of test classes (10) and calling two methods per class.
> Proposed minor cleanup change to 3.1.x branch

- src/java/ognl/ListPropertyAccessor.java
Minor fix:
- Comment out a system.out.println() call that appears to be
debugging-related.
- All other system.out.println calls in OGNL are already commented out.
> Minor fix: Comment out missed debugging system.out.println call

- src/java/ognl/AccessibleObjectHandler.java
- src/java/ognl/AccessibleObjectHandlerJDK9Plus.java
- src/java/ognl/AccessibleObjectHandlerPreJDK9.java
- src/java/ognl/DefaultMemberAccess.java
- src/java/ognl/OgnlRuntime.java
- src/test/java/ognl/OgnlRuntimeTest.java
- src/test/java/ognl/TestOgnlRuntime.java
- src/test/java/org/ognl/test/objects/GenericServiceImpl.java
Proposed OGNL enhancement:
- Implement mechanism to avoid "Illegal Reflective Access" warnings in JDK9+, with fallback to normal reflection.  Users can force usage of normal reflection in JDK9+ using a Java option (environment) flag if needed.
- Add interface to decouple AccessibleObject processing (easier support for future Java reflection changes).
- Add mechanism to check for JDK version (allows decision on access mechanism to use).
- Implement a stricter invocation mechanism by default to limit certain invocations.  Users can disable the stricter invocation using a Java option (environment) flag if needed.
- Adds additional unit tests for the changes (insofar as they can be tested).
> Proposed OGNL enhancement (alt. reflective access for JDK9+, enh. invocation control):

- src/main/java/ognl/OgnlOps.java
- src/test/java/org/ognl/test/ArithmeticAndLogicalOperatorsTest.java
When comparing non-numeric objects that do not implement `Comparable` interface, OGNL would throw an exception if they are not equal (so `a == b` is either true or an exception for these objects)
https://github.com/jkuhnert/ognl/blob/master/src/main/java/ognl/OgnlOps.java#L93
e.g.
```java
Map<String, Object> map = new HashMap<String, Object>();
map.put("a", new Object());
map.put("b", new Object());
// same object, result is true
assertTrue((Boolean)Ognl.getValue("a == a", map));
// different object, throws an exception instead of returning false
assertFalse((Boolean)Ognl.getValue("a == b", map));
```
This PR addresses that.
Note that it doesn't make sense to make the check inside `OgnlOps::compareWithConversion`, because that method is used by `OgnlOps::less`, in which case it still …
> Compare non-comparable objects by equals only

- pom.xml
- src/java/ognl/OgnlRuntime.java
- src/test/java/ognl/OgnlRuntimeTest.java
OGNL improve getter/setter detection algorithm:
- Add detail to isDefaultMethod() method comment.
- Add a new isNonDefaultPublicInterfaceMethod() method.
- Modify collectAccessors() method to consider public interface methods in addition to default methods.
- Modify _getGetMethod() to prefer the first valid public getter over other getters, then the first valid public non-Default interface getter and lastly the first getter of any kind.
- Modify _getSetMethod() to prefer the first valid public setter over other setters, then the first valid public non-Default interface setter and lastly the first setter of any kind.
> OGNL improve getter/setter detection algorithm:

- pom.xml
- src/java/ognl/OgnlRuntime.java
- src/test/java/ognl/TestOgnlRuntime.java
Attempt to resolve issue #34:
- Add a clearAdditionalCache() method to clear some additional cache elements.
Using a separate method as changing the behaviour of clearCache() could negatively impact existing usage.
- Added missing synchronization within clearCache() for many elements that should have synchronization for modifications.
> Cache clearing enhancement (clear additional cache, synchronization fix):

- pom.xml
- src/java/ognl/OgnlRuntime.java
Falls back to getXXX on SecurityException to be more adaptable for environments that have a SecurityManager applied.
> not fail on getDeclaredXXX when user has used a SecurityManager

- src/java/ognl/DefaultClassResolver.java
Backport PR#46 from 3.2.x to 3.1.x (cherry-pick).
One small change required as "`<>`" notation not supported with JDK 5/6 code compliance setting for 3.1.x.
> Backport PR#46 from 3.2.x to 3.1.x (cherry-pick)

- src/java/ognl/OgnlOps.java
- src/test/java/org/ognl/test/ArithmeticAndLogicalOperatorsTest.java
Backport PR#78 from 3.2.x to 3.1.x (cherry-pick) - Merge pull request #78 from peteruhnak/master.
Compare non-comparable objects by equals only
(cherry picked from commit 937fd071b99a7da1230a64d724aa72b96e1fff68)
> Backport PR#78 from 3.2.x to 3.1.x (cherry-pick)

- pom.xml
- src/main/java/ognl/OgnlRuntime.java
- src/test/java/ognl/TestOgnlRuntime.java
Forward-port PR#77 from 3.1.x to 3.2.x (cherry-pick).
Cache clearing enhancement (clear additional cache, synchronization fix) #70
The cherry-pick was clean, but one line in the unit test had to be changed (use of deprecated method in the test caused a failure, but was simple to correct).
> Forward-port PR#77 from 3.1.x to 3.2.x (cherry-pick)

- src/main/java/ognl/OgnlRuntime.java
- src/test/java/ognl/OgnlRuntimeTest.java
Forward-port PR#70 from 3.1.x to 3.2.x (cherry-pick).
Merge pull request #70 from JCgH4164838Gh792C124B5/localOGNL_3_1B2
Proposed minor cleanup change to 3.1.x branch
(cherry picked from commit 7d417f0f8e9bcf369400f566424d458fe7894a58)
#	src/main/java/ognl/OgnlRuntime.java
Kept `checkPermission` element from cherry-pick, even though it is related to
ongoing `SecurityManager` logic changes in 3.1.x.
Modified the lower block that was in conflict to use `checkPermission`
instead of a redundant Map get, and provided a TODO comment for it to be
removed if/when the `SecurityManager` logic from 3.1.x is merged into 3.2.x.
> Forward-port PR#70 from 3.1.x to 3.2.x (cherry-pick)

- pom.xml
- src/main/java/ognl/AccessibleObjectHandler.java
- src/main/java/ognl/AccessibleObjectHandlerJDK9Plus.java
- src/main/java/ognl/AccessibleObjectHandlerPreJDK9.java
- src/main/java/ognl/OgnlRuntime.java
- src/main/java/ognl/security/OgnlSecurityManager.java
- src/main/java/ognl/security/OgnlSecurityManagerFactory.java
- src/main/java/ognl/security/UserMethod.java
- src/test/java/ognl/DefaultMemberAccess.java
- src/test/java/ognl/OgnlRuntimeTest.java
- src/test/java/ognl/TestOgnlRuntime.java
- src/test/java/org/ognl/test/objects/GenericService.java
- src/test/java/org/ognl/test/objects/GenericServiceImpl.java
- src/test/resources/test.properties
Forward-port PR#69, PR#74 and PR#75 together from 3.1.x to 3.2.x (cherry-pick)
This PR seeks to cherry-pick the changes from PRs #69, #74 and #75 together as a combined set.
Trying to cherry-pick them individually resulted in additional headaches (since both later PRs build on top of the PR#69), so this PR cherry-picked each PR in sequence and resolved change conflicts manually for the 3.2.x branch.
Since there are a large number of changes when taken altogether this PR should be reviewed carefully before accepting.
**Note**:  For each of the 1st two cherry-picks _Git mapped all new files_ to locations under `/src/etc/` for unknown reasons.  The files were manually placed in their proper locations and the `/src/etc/` versions were deleted.  If there's a different way to handle that …
> Forward-port PR#69, PR#74 and PR#75 together from 3.1.x to 3.2.x (cherry-pick)

- src/java/ognl/Ognl.java
- src/test/java/org/ognl/test/enhance/TestExpressionCompiler.java
Proposed enhancement to Y. Zamani's change in PR#82.
- Apply methods to control changes to the expressionMaxLength.
- Appy minimal controls to ensure consistency and visibility of changes to
expressionMaxLength.
- Provide unit tests for the behaviour of expressionMaxLength and the new
methods.
> Proposed enhancement to expression max length functionality (control changes, visibility, unit tests)

- pom.xml
- src/java/ognl/ASTConst.java
- src/java/ognl/ASTMethod.java
- src/java/ognl/ASTProperty.java
- src/java/ognl/AccessibleObjectHandler.java
- src/java/ognl/AccessibleObjectHandlerJDK9Plus.java
- src/java/ognl/AccessibleObjectHandlerPreJDK9.java
- src/java/ognl/DefaultMemberAccess.java
- src/java/ognl/Evaluation.java
- src/java/ognl/EvaluationPool.java
- src/java/ognl/JavaCharStream.java
- src/java/ognl/JavaSource.java
- src/java/ognl/MemberAccess.java
- src/java/ognl/Node.java
- src/java/ognl/NullHandler.java
- src/java/ognl/ObjectArrayPool.java
- src/java/ognl/ObjectIndexedPropertyDescriptor.java
- src/java/ognl/ObjectPropertyAccessor.java
- src/java/ognl/OgnlContext.java
- src/java/ognl/OgnlOps.java
- src/java/ognl/OgnlParser.java
- src/java/ognl/OgnlParserTokenManager.java
- src/java/ognl/OgnlRuntime.java
- src/java/ognl/ParseException.java
- src/java/ognl/SimpleNode.java
- src/java/ognl/Token.java
- src/java/ognl/TokenMgrError.java
- src/java/ognl/enhance/ExpressionCompiler.java
- src/java/ognl/enhance/LocalReference.java
- src/java/ognl/security/UserMethod.java
Fix all JavaDoc warnings/errors that caused build failures when executing the Maven build with JDK8 and JDK11.
- Modified any JavaDoc entries as required in all source files (often adding missing @param, @return and @throws elements).  Some HTML escaping was also required, as well as bad tag formatting.
- Added source specifier and API link location to the project pom's javadoc-plugin entry
(see https://issues.apache.org/jira/browse/MJAVADOC-562 and https://issues.apache.org/jira/browse/MJAVADOC-615 for background).
- Build succeeded with JDK 7u79, 8u201, 11.0 and 11.0.4.
> Fix JavaDoc warnings/errors causing build failures with JDK8 and JDK11

- src/main/java/ognl/OgnlRuntime.java
- src/test/java/ognl/OgnlRuntimeTest.java
> Resolves problem with setting varargs parameter

- src/main/java/ognl/DefaultClassResolver.java
- src/test/java/ClassInDefaultPackage.java
- src/test/java/ognl/DefaultClassResolverTest.java
`DefaultClassResolver#classForName()` throws `ClassNotFoundException` if the specified class is in the default package (i.e. no dot in the className).
Using the default package should be avoided, but we have received a few bug reports about it.
https://github.com/mybatis/mybatis-3/issues/1524
https://github.com/mybatis/mybatis-3/issues/1768
And the reporters said that it was working fine with the older versions, so it probably is related to #46 .
To write a test, I had to create a class in the default package.
If you don't like it, I will remove the class along with the test.
The comment in the source might be good enough to avoid regression.
> DefaultClassResolver should resolve classes in the default package

- pom.xml
- src/java/ognl/Ognl.java
Update source/target level for OGNL 3.1.x to JDK 1.7.
- Update pom.xml with source/target 1.7 as per L. Lenart comment in PR#89.
- Update surefire plugin to latest 2.x available.
- Update javadoc comment in Ognl class causing build failure in JDK 8/11.
> Update source/target level for OGNL 3.1.x to JDK 1.7.

- src/main/java/ognl/OgnlOps.java
- src/test/java/org/ognl/test/ArithmeticAndLogicalOperatorsTest.java
WW-5043 Enum comparison failure fix:
- Improve OgnlOps.compareWithConversion() to handle special case of
enumerated types (Enum) with element bodies.
- Add additional equality and inequality unit tests for enumerated types.
(cherry picked from commit 55515c07789d8683f965e4bf7f0ec8b3d2702e18)
> WW-5043 Enum comparison failure fix (cherry-pick for 3.2.x)

- src/java/ognl/OgnlOps.java
- src/test/java/org/ognl/test/ArithmeticAndLogicalOperatorsTest.java
WW-5043 Enum comparison failure fix:
- Improve OgnlOps.compareWithConversion() to handle special case of  enumerated types (Enum) with element bodies.
- Add additional equality and inequality unit tests for enumerated types.
> WW-5043 Enum comparison failure fix

- src/main/java/ognl/OgnlContext.java
Proposed fix for Issue #81:
- Drops OgnlContext(Map values) constructor that always fails with an
Exception.
- Additional comments for remaining two constructors.
- Changed constructor to ensure _values Map can no longer be null.
- Added comments to setValues(Map value) and getValues() for clarity.
- Added @Override annotations to Map interface methods.
> Proposed fix for Issue #81 (deprecated constructor always throws an exception)

- src/main/java/ognl/OgnlRuntime.java
- src/test/java/ognl/TestOgnlRuntime.java
Considering the following two classes, `OgnlRuntime.getReadMethod(PublicChild.class, "name")` should return the `getName()` method, but it returns `null` instead.
```java
package pkg1;
class PkgPrivateParent {
public String getName() {
return "";
}
}
```
```java
package pkg1;
public class PublicChild extends PkgPrivateParent {
}
```
In the `getReadMethod()`, candidate methods are checked by `isMethodCallable()` which returns `false` for a bridge method even though it is callable.
I simply removed the 'is callable' check from `getReadMethod()` and there is no broken test.
p.s.
Note that this bug does not exists in `OgnlRuntime#getWriteMethod()` because it internally uses `BeanInfo#getMethodDescriptors()[i]#getMethod()#getModifiers()` which returns a different value than …
> `OgnlRuntime#getReadMethod()` returns `null` if the method is a bridge method

- src/main/java/ognl/OgnlRuntime.java
Minor cleanup fix:
- Removal of unneeded call (todo) in OgnlRuntime.invokeMethod() since the
SecurityManager sandbox logic has been merged from 3.1.x to 3.2.x.  Same
logic as in 3.1.x.
- Avoid extra getModifiers() call in OgnlRuntime.setFieldValue(), same
logic as in 3.1.x.
> Minor cleanup for 3.2.x, related to previous 3.1.x merges

- src/main/java/ognl/OgnlRuntime.java
- src/test/java/ognl/race/Base.java
- src/test/java/ognl/race/Persion.java
- src/test/java/ognl/race/RaceTestCase.java
I found a race condition problem which cause to throw NoSuchPropertyException when there are to many threads since version 3.1.2. Although it was resolved by trying to call method of "getReadMethod", it will loss some performance,  I think it is the best way  to resolve  race condition.
> resolve race condition problem

- src/main/java/ognl/AbstractMemberAccess.java
- src/main/java/ognl/Ognl.java
> Introduces AbstractMemberAccess to allow create it on-fly

- src/main/java/ognl/OgnlRuntime.java
- src/test/java/ognl/TestOgnlRuntime.java
Follow-up to PR #104.
Small updates to OgnlRuntime, attempting to ensure more consistent behaviour for JDK7-11.
- Update OgnlRuntime isMethodCallable().  Removed (now) unnecessary isJDK15 check, added clearer logic and explanatory JavaDoc comments.
- Added OgnlRuntime isMethodCallable_BridgeOrNonSynthetic() for specialized usage such as choosing valid Read and Write methods.
- Made checks in getReadMethod() and getWiteMethod symmetric again.
- Added new unit tests to confirm expected behaviour with respect to bridge methods and synthetic methods.
> Update isMethodCallable() logic, re-introduce its usage for getReadMethod()

- src/main/java/ognl/Ognl.java
- src/main/java/ognl/OgnlRuntime.java
- src/test/java/org/ognl/test/ChainTest.java
- src/test/java/org/ognl/test/MethodTest.java
- src/test/java/org/ognl/test/VarArgsMethodTest.java
> Adds support for null varargs

- pom.xml
- src/test/java/org/ognl/test/enhance/TestExpressionCompiler.java
Existing test processing issue fixes:
- Add two tests that were missing from surefire builds.
- Fix test_ApplyExpressionMaxLength() test issue not seen due to test not running during automated builds.
- Add finally guard to Improve test_ApplyExpressionMaxLength() and test_FreezeThawExpressionMaxLength() to restore default state even if the test fails, otherwise it can make other tests appear to fail due to side-effects.
> Change to ensure two existing tests are called by automation, plus minor test correction

- src/main/java/ognl/OgnlOps.java
- src/test/java/ognl/OgnlOpsTest.java
Originally, found on StackOverflow - https://stackoverflow.com/questions/66138007/struts-ognl-long-overflow
> WW-5118 Fix OgnlOps equal

- src/main/java/ognl/ASTMethod.java
- src/main/java/ognl/ASTStaticField.java
- src/main/java/ognl/OgnlRuntime.java
- src/test/java/org/ognl/test/VarArgsMethodTest.java
- src/test/java/org/ognl/test/objects/Simple.java
This PR improves handling of VarArgs by OGNL. Previously OGNL was not able to handle passing a single argument to a method with VarArgs also it couldn't properly apply non-`Object` VarArgs.
Closes #125
> Improves handling VarArgs

- src/main/java/ognl/OgnlOps.java
Hello @lukaszlenart ,
javac works fine, but Eclipse JDT requires explicit casting.
It seems that the JLS is not clear about this.
> Explicitly cast the Enum#compareTo argument

- src/main/java/ognl/OgnlRuntime.java
- src/test/java/ognl/OgnlRuntimeTest.java
As reported in #143 , making a method accessible is problematic in recent versions of Java ('illegal reflective access' warning on 9+ and InaccessibleObjectException on 16+).
This PR avoids some illegal reflective accesses that I found.
Please see the log message of each commit for the details.
> Avoid illegal reflective access when possible

- src/main/java/ognl/enhance/ExpressionCompiler.java
Addresses #160 by pointing Javassist at a neighbour (a class in the same package) class of the class we're generating, allowing it to avoid using the deprecated `ClassLoader.defineClass` (which now requires 'add-opens' to use because Javassist must use reflection to make the method visible), and instead use `MethodHandles`.
This implementation introduces a protected method `instantiateClass` that can be overridden by `ExpressionCompiler` subclassers who are customising the exact mechanics of the class instantiation process if needed.
> Update ExpressionCompiler to run on JDK17+ without 'add-opens' JVM opt using Javassist ClassPool.toClass overload that takes a neighbour class

- .github/workflows/maven.yml
- .mvn/wrapper/maven-wrapper.properties
- src/main/java/ognl/ObjectPropertyAccessor.java
- src/main/java/ognl/OgnlRuntime.java
- src/test/java/ognl/ExcludedObjectMemberAccess.java
- src/test/java/ognl/TestObjectPropertyAccessor.java
- src/test/java/ognl/TestOgnlRuntime.java
> Cherry-picks "WW-5417 update OgnlRuntime & ObjectPropertyAccessor to do access check for set field value"

- src/main/java/ognl/ObjectPropertyAccessor.java
- src/main/java/ognl/OgnlContext.java
- src/main/java/ognl/OgnlRuntime.java
- src/test/java/ognl/OgnlContextTest.java
- src/test/java/ognl/TestObjectPropertyAccessor.java
current implementation of getting property using `ObjectPropertyAccessor` will firstly try to find get method of target property,
if no get method found then try to find read method. If read method exist returns the return value of the read method。Sometimes read method does not directly returns the value of property. For example   the class `org.apache.kafka.clients.consumer.internals.Fetcher` , it has a property `completedFetches`, and a method `hasCompletedFetches` which will be recognized as a read method of the property `completedFetches`,  it returns a boolean value instead of the actural value of `completedFetches`. But what I need is to get the elements of ConcurrentLinkedQueue. So I think we should offer a parameter to ignore detecting read method in this case.
```
public class …
```
> add parameter ignoreReadMethod in ObjectPropertyAccessor

- src/main/java/ognl/Ognl.java
- src/test/java/ognl/test/ShortCircuitingExpressionTest.java
> Sets root on context if null

- src/main/java/ognl/Ognl.java
- src/test/java/ognl/test/OgnlContextCreateTest.java
- src/test/java/ognl/test/ShortCircuitingExpressionTest.java
- src/test/java/ognl/test/objects/Simple.java
> Reuses ClassResolver and TypeConverter of old OgnlContext
